sequenceDiagram
    Tamu->>Resepsionis: Tunjukkan identitas & kode
    Resepsionis->>Sistem: Cari data reservasi
    Sistem-->>Resepsionis: Tampilkan data disetujui
    Resepsionis->>Sistem: Konfirmasi check-in
    Sistem->>Sistem: Ubah kamar jadi Ditempati
